name: map-cv
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.11
  - pytorch
  - torchvision
  - torchaudio
  - pytorch-cuda=12.1
  
  - gdal
  - geopandas
  - rasterio
  - shapely
  - pyproj
  
  - pip
  - pip:
    - transformers==4.41.2
    - datasets==2.19.1
    - accelerate==0.30.1
    - easyocr
    - segmentation-models-pytorch
    - opencv-python-headless
    - pytesseract
    - scikit-image
    - albumentations
    - matplotlib
    - pandas
    - scikit-learn
    - optuna
    - tqdm